import '../models/senzhub_models.dart';

class MockDataService {
  const MockDataService._();

  static const List<OnboardingSlide> onboardingSlides = [
    OnboardingSlide(
      title: 'Smart LPG monitoring',
      subtitle: 'Track live gas conditions, maintain safe thresholds, and monitor your system instantly.',
      icon: 'shield',
      badge: 'SAFE',
    ),
    OnboardingSlide(
      title: 'Instant safety alerts',
      subtitle: 'Stay informed when warning conditions arise and when the system acts to protect you.',
      icon: 'alert',
      badge: 'LIVE',
    ),
    OnboardingSlide(
      title: 'Automatic emergency protection',
      subtitle: 'Valve closure and emergency logic remain with the ESP32 safety layer while the app monitors and responds.',
      icon: 'lock',
      badge: 'PROTECTED',
    ),
  ];

  static final SystemSnapshot systemSnapshot = SystemSnapshot(
    gasLevelPpm: 2840,
    warningThreshold: 3200,
    dangerThreshold: 3700,
    gasStatus: SafetyLevel.safe,
    valveState: ValveState.closed,
    battery: 92,
    gsmSignalCsq: 22,
    gsmSignalQuality: 'Good',
    systemOnline: true,
    powerSource: PowerSource.ac,
    deviceId: 'SENZHUB-001',
    location: 'Kitchen • Zone A',
    latestAlert: AlertItem(
      title: 'Gas level warning detected',
      message: 'Reading is trending upward but remains below emergency threshold.',
      severity: AlertSeverity.warning,
      timestamp: '12 min ago',
      gasLevel: 2840,
      action: 'Monitoring continued',
    ),
  );

  static const List<AlertItem> alerts = [
    AlertItem(
      title: 'Gas level warning detected',
      message: 'Gas concentration moved above the preferred safety band.',
      severity: AlertSeverity.warning,
      timestamp: '12 min ago',
      gasLevel: 3320,
      action: 'Alert acknowledged',
    ),
    AlertItem(
      title: 'Gas level returned to safe',
      message: 'System normalized after warning-state review.',
      severity: AlertSeverity.info,
      timestamp: '1 hour ago',
      gasLevel: 2860,
      action: 'Auto monitor resumed',
    ),
    AlertItem(
      title: 'Emergency danger detected',
      message: 'Danger threshold exceeded and safety logic activated.',
      severity: AlertSeverity.critical,
      timestamp: '3 hours ago',
      gasLevel: 3815,
      action: 'Valve closed automatically',
    ),
    AlertItem(
      title: 'Valve automatically closed',
      message: 'Solenoid valve was isolated as a protective response.',
      severity: AlertSeverity.danger,
      timestamp: 'Yesterday',
      gasLevel: 3740,
      action: 'Flow isolated',
    ),
    AlertItem(
      title: 'GSM alert sent',
      message: 'Remote notification delivered to the administrator channel.',
      severity: AlertSeverity.info,
      timestamp: 'Yesterday',
      gasLevel: 0,
      action: 'SMS dispatched',
    ),
    AlertItem(
      title: 'Battery low',
      message: 'Battery reserve dropped below preferred backup threshold.',
      severity: AlertSeverity.warning,
      timestamp: '2 days ago',
      gasLevel: 0,
      action: 'Power source switched to AC',
    ),
    AlertItem(
      title: 'System diagnostic warning',
      message: 'Daily health check identified a minor offset in sensor calibration.',
      severity: AlertSeverity.warning,
      timestamp: '3 days ago',
      gasLevel: 0,
      action: 'Scheduled inspection',
    ),
  ];

  static const List<DeviceRecord> devices = [
    DeviceRecord(
      id: 'SENZHUB-001',
      serialNumber: 'SENZHUB-001',
      status: DeviceStatus.online,
      location: 'Kitchen • Zone A',
      lastCommunication: '2 sec ago',
      gasStatus: 'SAFE',
      valveState: ValveState.closed,
      battery: 92,
      gsmSignalCsq: 22,
      gsmSignalQuality: 'Good',
      powerSource: PowerSource.ac,
    ),
  ];

  static const List<DiagnosticItem> diagnostics = [
    DiagnosticItem(
      name: 'MQ-6 Sensor',
      status: 'Nominal',
      lastChecked: '18 sec ago',
      message: 'Stable output with low drift.',
    ),
    DiagnosticItem(
      name: 'ESP32',
      status: 'Healthy',
      lastChecked: '12 sec ago',
      message: 'Core controller responsive and synchronized.',
    ),
    DiagnosticItem(
      name: 'GSM Module',
      status: 'Connected',
      lastChecked: '32 sec ago',
      message: 'Signal quality: Good • Signal strength: 22/31 • Network: Connected',
    ),
    DiagnosticItem(
      name: 'SIM',
      status: 'Active',
      lastChecked: '1 min ago',
      message: 'Network registration stable.',
    ),
    DiagnosticItem(
      name: 'Solenoid Valve',
      status: 'Closed',
      lastChecked: '8 sec ago',
      message: 'Safety interlock is engaged.',
    ),
    DiagnosticItem(
      name: 'Battery',
      status: '92%',
      lastChecked: '30 sec ago',
      message: 'Charging remains stable and healthy.',
    ),
    DiagnosticItem(
      name: 'Power Supply',
      status: 'AC',
      lastChecked: '15 sec ago',
      message: 'Primary power source active.',
    ),
    DiagnosticItem(
      name: 'System',
      status: 'Online',
      lastChecked: '5 sec ago',
      message: 'Monitoring cycle running normally.',
    ),
  ];

  static const List<SdgGoal> sdgGoals = [
    SdgGoal(
      number: 'SDG 1',
      name: 'No Poverty',
      icon: 'sdg01',
      summary: 'End poverty in all its forms everywhere and support resilient, safe households.',
      purpose: 'This goal seeks to reduce extreme poverty, improve access to basic services, and build resilience for people facing vulnerability.',
      contribution: 'SENZHUB is most relevant where safer home systems and practical household support can reduce everyday risk for families and vulnerable communities.',
      senzhubRelation: 'SENZHUB contributes to safer home operations and clearer awareness of household risk, which can support basic stability and resilience for households.',
      targets: [
        SdgTarget(number: '1.1', text: 'By 2030, eradicate extreme poverty for all people everywhere, currently measured as people living on less than \$1.25 a day.'),
        SdgTarget(number: '1.2', text: 'By 2030, reduce at least by half the proportion of men, women and children of all ages living in poverty in all its dimensions according to national definitions.'),
        SdgTarget(number: '1.3', text: 'Implement nationally appropriate social protection systems and measures for all, including floors, and by 2030 achieve substantial coverage of the poor and the vulnerable.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 2',
      name: 'Zero Hunger',
      icon: 'sdg02',
      summary: 'End hunger, achieve food security, improve nutrition, and promote sustainable agriculture.',
      purpose: 'This goal focuses on food security, sustainable agriculture, and the reduction of malnutrition around the world.',
      contribution: 'The app does not claim to solve hunger, but it supports safer household energy awareness and practical infrastructure that can contribute to stable everyday living conditions.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '2.1', text: 'By 2030, end hunger and ensure access by all people, in particular the poor and those in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round.'),
        SdgTarget(number: '2.2', text: 'By 2030, end all forms of malnutrition, including achieving, by 2025, the internationally agreed targets on stunting and wasting in children under 5 years of age.'),
        SdgTarget(number: '2.3', text: 'By 2030, double the agricultural productivity and incomes of small-scale food producers, in particular women, indigenous peoples, family farmers, pastoralists and fishers.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 3',
      name: 'Good Health and Well-Being',
      icon: 'sdg03',
      summary: 'Ensure healthy lives and promote well-being for all at every age.',
      purpose: 'This goal works to reduce preventable deaths, strengthen health systems, and improve health outcomes across communities.',
      contribution: 'SENZHUB supports safer homes by helping users detect elevated gas conditions, act early, and understand household LPG safety.',
      senzhubRelation: 'SENZHUB supports safer household gas monitoring and user awareness, which is aligned with improving everyday health and safety conditions in the home.',
      targets: [
        SdgTarget(number: '3.1', text: 'By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births.'),
        SdgTarget(number: '3.2', text: 'By 2030, end preventable deaths of newborns and children under 5 years of age, with all countries aiming to reduce neonatal mortality to at least as low as 12 per 1,000 live births.'),
        SdgTarget(number: '3.3', text: 'By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases and combat hepatitis, water-borne diseases and other communicable diseases.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 4',
      name: 'Quality Education',
      icon: 'sdg04',
      summary: 'Ensure inclusive and equitable quality education and promote lifelong learning opportunities.',
      purpose: 'This goal aims to expand access to quality education, literacy, and lifelong skills for every learner.',
      contribution: 'SENZHUB helps users understand safe household systems through simple, explanatory guidance and clear information design.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '4.1', text: 'By 2030, ensure that all girls and boys complete free, equitable and quality primary and secondary education leading to relevant and effective learning outcomes.'),
        SdgTarget(number: '4.2', text: 'By 2030, ensure that all girls and boys have access to quality early childhood development, care and pre-primary education so that they are ready for primary education.'),
        SdgTarget(number: '4.3', text: 'By 2030, ensure equal access for all women and men to affordable and quality technical, vocational and tertiary education, including university.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 5',
      name: 'Gender Equality',
      icon: 'sdg05',
      summary: 'Achieve gender equality and empower all women and girls.',
      purpose: 'This goal promotes equal rights, opportunities, and protection for women and girls in every part of society.',
      contribution: 'SENZHUB supports household safety access in a way that is practical and inclusive for all users, regardless of background.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '5.1', text: 'End all forms of discrimination against all women and girls everywhere.'),
        SdgTarget(number: '5.2', text: 'Eliminate all forms of violence against all women and girls in the public and private spheres, including trafficking and sexual and other types of exploitation.'),
        SdgTarget(number: '5.3', text: 'Eliminate all harmful practices, such as child, early and forced marriage and female genital mutilation.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 6',
      name: 'Clean Water and Sanitation',
      icon: 'sdg06',
      summary: 'Ensure availability and sustainable management of water and sanitation for all.',
      purpose: 'This goal seeks to secure clean water, improved sanitation, and sustainable water management in communities worldwide.',
      contribution: 'SENZHUB is not directly a water system, but its approach to safe, understandable household infrastructure reflects the broader need for resilient everyday essentials.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '6.1', text: 'By 2030, achieve universal and equitable access to safe and affordable drinking water for all.'),
        SdgTarget(number: '6.2', text: 'By 2030, achieve access to adequate and equitable sanitation and hygiene for all and end open defecation, paying special attention to the needs of women and girls and those in vulnerable situations.'),
        SdgTarget(number: '6.3', text: 'By 2030, improve water quality by reducing pollution, eliminating dumping and minimizing release of hazardous chemicals and materials, halving the proportion of untreated wastewater and substantially increasing recycling and safe reuse globally.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 7',
      name: 'Affordable and Clean Energy',
      icon: 'sdg07',
      summary: 'Ensure access to affordable, reliable, sustainable and modern energy for all.',
      purpose: 'This goal is about energy access, reliability, clean-power transitions, and reducing energy poverty.',
      contribution: 'SENZHUB is directly aligned with safer household LPG awareness and monitoring, helping users better understand energy systems and risk conditions.',
      senzhubRelation: 'SENZHUB supports safer, more informed household energy use and contributes to a practical awareness layer around LPG consumption and system reliability.',
      targets: [
        SdgTarget(number: '7.1', text: 'By 2030, ensure universal access to affordable, reliable and modern energy services.'),
        SdgTarget(number: '7.2', text: 'By 2030, increase substantially the share of renewable energy in the global energy mix.'),
        SdgTarget(number: '7.3', text: 'By 2030, double the global rate of improvement in energy efficiency.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 8',
      name: 'Decent Work and Economic Growth',
      icon: 'sdg08',
      summary: 'Promote sustained, inclusive and sustainable economic growth, full and productive employment, and decent work for all.',
      purpose: 'This goal supports productive employment, safe working conditions, and sustained economic opportunity.',
      contribution: 'The app reflects modern, practical household technology and user-friendly safety systems that can support everyday productivity and infrastructure awareness.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '8.1', text: 'Sustain per capita economic growth in accordance with national circumstances and, in particular, at least 7 per cent gross domestic product growth per annum in the least developed countries.'),
        SdgTarget(number: '8.2', text: 'Achieve higher levels of economic productivity through diversification, technological upgrading and innovation, including through a focus on high-value added and labour-intensive sectors.'),
        SdgTarget(number: '8.3', text: 'Promote development-oriented policies that support productive activities, decent job creation, entrepreneurship, creativity and innovation, and encourage the formalization and growth of micro-, small- and medium-sized enterprises.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 9',
      name: 'Industry, Innovation and Infrastructure',
      icon: 'sdg09',
      summary: 'Build resilient infrastructure and promote inclusive and sustainable industrialization.',
      purpose: 'This goal focuses on resilient infrastructure, innovation, research, and sustainable industrial development.',
      contribution: 'SENZHUB is a clear example of practical innovation in embedded systems, sensing, connectivity, and consumer safety design.',
      senzhubRelation: 'SENZHUB is aligned with this goal through sensing, embedded control, connectivity, and household safety technology designed for practical everyday use.',
      targets: [
        SdgTarget(number: '9.1', text: 'Develop quality, reliable, sustainable and resilient infrastructure, including regional and transborder infrastructure, to support economic development and human well-being.'),
        SdgTarget(number: '9.2', text: 'Promote inclusive and sustainable industrialization and, by 2030, significantly raise industry’s share of employment and gross domestic product in line with national circumstances.'),
        SdgTarget(number: '9.3', text: 'Increase the access of small-scale industrial and other enterprises, in particular in developing countries, to financial services, affordable credit and their integration into value chains and markets.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 10',
      name: 'Reduced Inequalities',
      icon: 'sdg10',
      summary: 'Reduce inequality within and among countries.',
      purpose: 'This goal works to reduce disparity in income, opportunity, and access to services and institutions.',
      contribution: 'Accessible safety information and user-friendly design can make critical home-protection guidance easier to understand for more people.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '10.1', text: 'By 2030, progressively achieve and sustain income growth of the bottom 40 per cent of the population at a rate higher than the national average.'),
        SdgTarget(number: '10.2', text: 'By 2030, empower and promote the social, economic and political inclusion of all, irrespective of age, sex, disability, race, ethnicity, origin, religion or economic or other status.'),
        SdgTarget(number: '10.3', text: 'Ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices and promoting appropriate legislation, policies and action in this regard.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 11',
      name: 'Sustainable Cities and Communities',
      icon: 'sdg11',
      summary: 'Make cities and human settlements inclusive, safe, resilient and sustainable.',
      purpose: 'This goal promotes safer, more inclusive urban life and resilient local systems for growing communities.',
      contribution: 'SENZHUB aligns with safer homes and small commercial spaces through early detection, monitoring, and protection strategies.',
      senzhubRelation: 'SENZHUB supports safer household and small-community living by improving monitoring and early awareness of gas-related risk.',
      targets: [
        SdgTarget(number: '11.1', text: 'By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums.'),
        SdgTarget(number: '11.2', text: 'By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations.'),
        SdgTarget(number: '11.5', text: 'By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 12',
      name: 'Responsible Consumption and Production',
      icon: 'sdg12',
      summary: 'Ensure sustainable consumption and production patterns.',
      purpose: 'This goal focuses on efficient resource use, waste reduction, and responsible production cycles.',
      contribution: 'SENZHUB supports more responsible LPG use by helping users monitor system status and act before unsafe conditions develop.',
      senzhubRelation: 'SENZHUB is aligned with this goal by encouraging responsible use and monitoring of household fuel systems to reduce waste, risk, and unnecessary inefficiency.',
      targets: [
        SdgTarget(number: '12.2', text: 'By 2030, achieve the sustainable management and efficient use of natural resources.'),
        SdgTarget(number: '12.4', text: 'By 2020, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, in accordance with agreed international frameworks, and significantly reduce their release to air, water and soil.'),
        SdgTarget(number: '12.5', text: 'By 2030, substantially reduce waste generation through prevention, reduction, recycling and reuse.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 13',
      name: 'Climate Action',
      icon: 'sdg13',
      summary: 'Take urgent action to combat climate change and its impacts.',
      purpose: 'This goal addresses climate resilience, mitigation, and urgent action to reduce carbon risk and environmental harm.',
      contribution: 'SENZHUB contributes to careful household energy awareness and safer fuel management without claiming large-scale climate impact.',
      senzhubRelation: 'SENZHUB can support more careful household energy awareness and safer fuel-system behavior, while keeping its role modest and practical rather than making broad climate claims.',
      targets: [
        SdgTarget(number: '13.1', text: 'Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries.'),
        SdgTarget(number: '13.2', text: 'Integrate climate change measures into national policies, strategies and planning.'),
        SdgTarget(number: '13.3', text: 'Improve education, awareness-raising and human and institutional capacity on climate change mitigation, adaptation, impact reduction and early warning.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 14',
      name: 'Life Below Water',
      icon: 'sdg14',
      summary: 'Conserve and sustainably use the oceans, seas and marine resources for sustainable development.',
      purpose: 'This goal protects ecosystems and marine biodiversity while supporting sustainable ocean use.',
      contribution: 'SENZHUB does not directly manage marine systems, but it supports a broader culture of responsible resource stewardship and safer energy practices.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '14.1', text: 'By 2025, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including marine debris and nutrient pollution.'),
        SdgTarget(number: '14.2', text: 'By 2020, sustainably manage and protect marine and coastal ecosystems to avoid significant adverse impacts, including by strengthening their resilience and taking action for their restoration.'),
        SdgTarget(number: '14.3', text: 'Minimize and address the impacts of ocean acidification, including through enhanced scientific cooperation at all levels.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 15',
      name: 'Life on Land',
      icon: 'sdg15',
      summary: 'Protect, restore and promote sustainable use of terrestrial ecosystems.',
      purpose: 'This goal protects biodiversity, forests, and land ecosystems while reducing desertification and land degradation.',
      contribution: 'SENZHUB supports the broader idea of responsible environmental care in everyday life and infrastructure decisions.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '15.1', text: 'By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services, in particular forests, wetlands, mountains and drylands, in line with obligations under international agreements.'),
        SdgTarget(number: '15.2', text: 'By 2020, promote the implementation of sustainable management of all types of forests, halt deforestation, restore degraded forests and substantially increase afforestation and reforestation globally.'),
        SdgTarget(number: '15.3', text: 'By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods, and strive to achieve a land degradation-neutral world.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 16',
      name: 'Peace, Justice and Strong Institutions',
      icon: 'sdg16',
      summary: 'Promote peaceful and inclusive societies, provide access to justice and build effective, accountable institutions.',
      purpose: 'This goal supports strong institutions, justice, and peaceful, inclusive communities.',
      contribution: 'Transparent safety monitoring and practical information access can support trust in local systems and household decision-making.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '16.1', text: 'Significantly reduce all forms of violence and related death rates everywhere.'),
        SdgTarget(number: '16.3', text: 'Promote the rule of law at the national and international levels and ensure equal access to justice for all.'),
        SdgTarget(number: '16.6', text: 'Develop effective, accountable and transparent institutions at all levels.'),
      ],
    ),
    SdgGoal(
      number: 'SDG 17',
      name: 'Partnerships for the Goals',
      icon: 'sdg17',
      summary: 'Strengthen the means of implementation and revitalize the global partnership for sustainable development.',
      purpose: 'This goal is about cooperation, finance, technology transfer, and shared implementation of the global agenda.',
      contribution: 'SENZHUB reflects the value of practical, collaborative technology solutions that can support smarter and safer everyday communities.',
      senzhubRelation: null,
      targets: [
        SdgTarget(number: '17.1', text: 'Strengthen domestic resource mobilization, including through international support to developing countries, to improve domestic capacity for tax and other revenue collection.'),
        SdgTarget(number: '17.2', text: 'Developed countries to implement fully their official development assistance commitments, including the commitment to achieve the target of 0.7 per cent of gross national income to official development assistance to developing countries and 0.15 to 0.20 per cent to least developed countries.'),
        SdgTarget(number: '17.3', text: 'Mobilize additional financial resources for developing countries from multiple sources.'),
      ],
    ),
  ];

  static const List<BookingItem> bookingHistory = [
    BookingItem(
      label: 'Current cylinder',
      value: '14.2 kg',
      detail: 'Remaining supply within expected range',
    ),
    BookingItem(
      label: 'Provider',
      value: 'SENZHUB Supply Co.',
      detail: 'Preferred partner',
    ),
    BookingItem(
      label: 'Schedule',
      value: '12 Oct • 10:00',
      detail: 'Delivery slot requested',
    ),
    BookingItem(
      label: 'Status',
      value: 'Queued',
      detail: 'Awaiting confirmation',
    ),
  ];

  static const List<double> gasTrendData = [
    2260,
    2480,
    2720,
    2950,
    3180,
    3360,
    3280,
    3000,
    2870,
    2840,
    3015,
    2920,
  ];
}
